### ISSUE TITLE
Placement coordinates never appended to element inline style

### ISSUE THREAD

**Issue by moniuch** [meiriko/ng2-pop-over#8] opened 2017-03-16 11:57 UTC
I have my custom table component which should use popover to display actions available for each data row. I open it programmatically:

```
(click)="doShowActions($event, actions)"

@ViewChild('actionPopover')
  actionPopover: PopOverComponent;

doShowActions($event, actions){
    console.log('showing actions', actions);
    this.actionPopover.show($event);
}

```
When I embed it in the component's HTML:

```
<pop-over #actionPopover [my]="'top left'" [at]="'bottom right'">
  <ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
  </ul>
</pop-over>  
```

it shows up, but the placement coordinates are never calculated and appended to the inline style, as they are in your demo. Thus, the popover displays below the page contents.
I made sure to set `body`s position to relative.
![screen shot 2017-03-16 at 12 55 56](https://cloud.githubusercontent.com/assets/681956/23995032/0536dab8-0a48-11e7-9d9c-70a596e44e8b.png)

Moreover, when I use `[anchor-to]="true"` I got an error message saying: `Cannot read property 'getBoundingClientRect' of undefined`

Would you have an idea what could be the source of these (I believe: related) problems?

**Comment by meiriko** [comment] 2017-03-16 12:22
I'll try to have a look at it. Is there a chance you can do a sample plnkr to show the problem?

**Comment by moniuch** [comment] 2017-03-16 12:55
I don't think I will be able to reproduce it - as I am working in a multi compound component environment. I just managed to resolve my problem purely accidentally by moving the <pop-over> element up in the components hierarchy. Would be really time consuming, I am sorry about that.

Now I am facing another one now, which is a momentary page re-render and reflow upon first invocation of popover after page load (a momentary yan of appearing and disappearing scrollbar on the body element). It could still be related to the original problem, but now at least the functionality is in place :)

**Comment by meiriko** [comment] 2017-03-16 12:58
Glad to here it was partially resolved. It might be due to absolute/fixed positioning issue. If you manage to reproduce the issue again in a simpler setup, please lemme know. Thx.

Do you use the pop-over in production or are you only prototyping?

Can I close this issue?

**Comment by moniuch** [comment] 2017-03-16 13:04
I am basically prototyping now. Yes, the issue can be closed. Thanks for your prompt response!

**Closed as completed** 2017-03-16 13:09 UTC
